In [1]:
import pandas as pd
import numpy as np
import os 
from langchain.document_loaders import PyPDFLoader, UnstructuredAPIFileIOLoader, PyPDFium2Loader
from langchain.document_loaders import PyPDFDirectoryLoader, DirectoryLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from pathlib import Path
import random

In [2]:
data_dir = 'TEXT_data'
inputdirectory = Path(f"./{data_dir}")
out_dir = data_dir
outputdirectory = Path(f"./TEXT_data/output")

In [3]:
import re

def fix_splitted_words_in_text(text):
    
    text = re.sub(r'\b(\w+)\s+ed\b', r'\1ed', text)
    text = re.sub(r'\bfi\s+rst\b', 'first', text)
    text = re.sub(r'\bi\s+t\b', 'it', text)
    text = re.sub(r'\bI\s+t\b', 'It', text)
    text = re.sub(r'\bT\s+he\b', 'The', text)
    text = re.sub(r'\bt\s+he\b', 'the', text)
    text = re.sub(r'\bIdentifi\s+cation\b', 'Identification', text)
    text = re.sub(r'\bidentifi\s+cation\b', 'identification', text)
    text = re.sub(r'\bO\s+nce\b', 'Once', text)
    text = re.sub(r'\bviTABLE\b', 'vi TABLE', text)
    text = re.sub(r'\bCONTENTSTABLE\b', 'CONTENTS TABLE', text)
    text = re.sub(r'\bfi\s+nd\b', 'find', text)
    text = re.sub(r'\bR\s+isk\b', 'Risk', text)
    text = re.sub(r'\beffi\s+ciency\b', 'efficiency', text)
    text = re.sub(r'\bsignifi\s+cant\b', 'significant', text)
    text = re.sub(r'\bdefi\s+ned\b', 'defined', text)
    text = re.sub(r'\bdefi\s+nes\b', 'defines', text)
    text = re.sub(r'\bE\s+ach\b', 'Each', text)
    text = re.sub(r'\bG\s+uide\b', 'Guide', text)
    text = re.sub(r'\bI\s+dentified\b', 'Identified', text)
    text = re.sub(r'\bR\s+isks\b', 'Risks', text)
    text = re.sub(r'\bdiffi\s+cult\b', 'difficult', text)
    text = re.sub(r'\bfi\s+nish\b', 'finish', text)
    text = re.sub(r'\bfi\s+ltered\b', 'filtered', text)
    text = re.sub(r'\bfi\s+ltering\b', 'filtering', text)
    text = re.sub(r'\bfi\s+ndings\b', 'findings', text)
    text = re.sub(r'\bfi\s+nding\b', 'finding', text)
    text = re.sub(r'\bC\s+urrent\b', 'Current', text)
    text = re.sub(r'\bbenefi\s+t\b', 'benefit', text)
    text = re.sub(r'\bspecifi\s+c\b', 'specific', text)
    text = re.sub(r'\bC\s+ritical\b', 'Critical', text)
    text = re.sub(r'\bpredefi\s+ned\b', 'predefined', text)
    text = re.sub(r'\bspecifi\s+cally\b', 'specifically', text)
    text = re.sub(r'\bconfi\s+dence\b', 'confidence', text)
    text = re.sub(r'\bfi\s+nancial\b', 'financial', text)
    text = re.sub(r'\bsuffi\s+cient\b', 'sufficient', text)
    text = re.sub(r'\bfi\s+nal\b', 'final', text)
    text = re.sub(r'\bdefi\s+nition\b', 'definition', text)
    text = re.sub(r'\bdefi\s+nitions\b', 'definitions', text)
    text = re.sub(r'\bDefi\s+nitions\b', 'Definitions', text)
    text = re.sub(r'\bC\s+onsolidated\b', 'Consolidated', text)
    text = re.sub(r'\bbeneﬁ\s+ts\b', 'benefits', text)
    text = re.sub(r'\bbenefi\s+ts\b', 'benefits', text)
    text = re.sub(r'\bI\s+dentifying\b', 'Identifying', text)
    text = re.sub(r'\binfl\s+uence\b', 'influence', text)
    text = re.sub(r'\bI\s+mpact\b', 'Impact', text)
    text = re.sub(r'\bC\s+ollection\b', 'Collection', text)
    text = re.sub(r'\bQ\s+ualitative\b', 'Qualitative', text)
    text = re.sub(r'\bA\s+ssessment\b', 'Assessment', text)
    text = re.sub(r'\bSpecifi\s+c\b', 'Specific', text)
    text = re.sub(r'\bS\s+ome\b', 'Some', text)
    text = re.sub(r'\brefl\s+ects\b', 'reflects', text)
    text = re.sub(r'\bP\s+artial\b', 'Partial', text)
    text = re.sub(r'\bR\s+esults\b', 'Results', text)
    text = re.sub(r'\bO\s+ften\b', 'Often', text)
    text = re.sub(r'\bS\s+uccess\b', 'Success', text)
    text = re.sub(r'\bT\s+ools\b', 'Tools', text)
    text = re.sub(r'\bD\s+ata\b', 'Data', text)
    text = re.sub(r'\bfi\s+nishing\b', 'finishing', text)
    text = re.sub(r'\bI\s+dentity\b', 'Identity', text)
    text = re.sub(r'\bO\s+verall\b', 'Overall', text)
    text = re.sub(r'\brefl\s+ected\b', 'reflected', text)
    text = re.sub(r'\bE\s+ffective\b', 'Effective', text)
    text = re.sub(r'\binfl\s+uenced\b', 'influenced', text)
    text = re.sub(r'\bspecifi\s+es\b', 'specifies', text)
    text = re.sub(r'\bP\s+roject\b', 'Project', text)
    text = re.sub(r'\bP\s+lanning\b', 'Planning', text)
    text = re.sub(r'\bE\s+laboration\b', 'Elaboration', text)
    text = re.sub(r'\bDefi\s+ne\b', 'Define', text)
    text = re.sub(r'\bS\s+pecifi\b', 'Specific', text)
    text = re.sub(r'\bQ\s+uantitative\b', 'Quantitative', text)
    text = re.sub(r'\bSpecifi\s+cally\b', 'Specifically', text)
    text = re.sub(r'\brefl\s+ect\b', 'reflect', text)
    text = re.sub(r'\bfi\s+t\b', 'fit', text)
    text = re.sub(r'\bdefi\s+ne\b', 'define', text)
    text = re.sub(r'\bspecifi\s+cation\b', 'specification', text)
    text = re.sub(r'\bsuffi\s+ciently\b', 'sufficiently', text)
    text = re.sub(r'\bconfi\s+guration\b', 'configuration', text)
    text = re.sub(r'\bR\s+esponses\b', 'Responses', text)
    text = re.sub(r'\baffi\s+nity\b', 'affinity', text)
    text = re.sub(r'\bprofi\s+le\b', 'profile', text)
    text = re.sub(r'\bM\s+itigation\b', 'Mitigation', text)
    text = re.sub(r'\bT\s+hese\b', 'These', text)
    text = re.sub(r'\bW\s+hile\b', 'While', text)
    text = re.sub(r'\bspeciﬁ\s+c\b', 'specific', text)
    
    return text

# Read the input text file, fix split words, and save the corrected text back to the file
def process_text_file(input_file_path, output_file_path):
    with open(input_file_path, 'r', encoding='utf-8') as file:
        text = file.read()
    
    # Apply the word-fixing function
    fixed_text = fix_splitted_words_in_text(text)
    
    # Write the corrected text to the output file
    with open(output_file_path, 'w', encoding='utf-8') as file:
        file.write(fixed_text)

# Example usage
input_file = 'risk_management_final.txt'
output_file = 'TEXT_data/risk_management_clean.txt'
process_text_file(input_file, output_file)

# Loading Data

In [4]:
loader = DirectoryLoader(inputdirectory, show_progress=True)
documents = loader.load()

splitter = RecursiveCharacterTextSplitter(
    chunk_size = 1500,
    chunk_overlap = 150,
    length_function = len,
    is_separator_regex = False,
)

pages = splitter.split_documents(documents)
print("Number of chunks =", len(pages))
print(pages[3].page_content)

  1%|          | 1/107 [00:04<08:01,  4.54s/it]

KeyboardInterrupt:

#### Create a dataframe of all the chunks

In [ ]:
from helpers.df_helpers import documents2Dataframe
df = documents2Dataframe(pages)
print(df.shape)
df.head()

(81, 3)

,text,source,chunk_id
0,CHAPTER 1 INTRODUCTION Project Management Inst...,TEXT_data\risk_management_clean.txt,2768ce07a7ce4409b50c55a51bcfe231
1,While tools and techniques are constantly evol...,TEXT_data\risk_management_clean.txt,a4a069a58ab945b2a887caea964e9612
2,CHAPTER 1 − INTRODUCTION 1.2 Project Risk Mana...,TEXT_data\risk_management_clean.txt,258c1aaf5ff44c4787b2191fbebc216b
3,The execution of the Project Risk Management p...,TEXT_data\risk_management_clean.txt,30bf81e392164841b10a855dc61c9a28
4,This allows for the gain of synergies and effi...,TEXT_data\risk_management_clean.txt,1159b05d34a343b0bd42243a3092d29c

In [ ]:
from helpers.df_helpers import df2Graph
from helpers.df_helpers import graph2Df

In [ ]:
concepts_list = df2Graph(df, model='mistral')

 [
       {
           "node_1": "Project Management Institute (PMI)",
           "node_2": "A Guide to the Project Management Body of Knowledge (PMBOK Guide – Fourth Edition)",
           "edge": "The Project Management Institute (PMI) practice standards are guides derived from 'A Guide to the Project Management Body of Knowledge (PMBOK Guide – Fourth Edition)'."
       },
       {
           "node_1": "Project Risk Management processes",
           "node_2": "PMBOK Guide – Fourth Edition",
           "edge": "The Project Risk Management processes are defined in 'A Guide to the Project Management Body of Knowledge (PMBOK Guide – Fourth Edition)'."
       },
       {
           "node_1": "Plan Risk Management",
           "node_2": "Chapter",
           "edge": "Each of the six processes, including Plan Risk Management, is described in a separate chapter."
       },
       {
           "node_1": "Perform Qualitative Risk Analysis",
           "node_2": "Chapter",
           "edge": "Each of the six processes, including Perform Qualitative Risk Analysis, is described in a separate chapter."
       },
       {
           "node_1": "Plan Risk Management",
           "node_2": "purpose and objectives of the process",
           "edge": "The 'purpose and objectives' of Plan Risk Management are addressed in the chapter dedicated to it."
       },
       {
           "node_1": "Perform Qualitative Risk Analysis",
           "node_2": "tools and techniques for the process",
           "edge": "The 'tools and techniques' for Perform Qualitative Risk Analysis are described in the chapter dedicated to it."
       }
   ] [
      {
          "node_1": "Tools and Techniques",
          "node_2": "Principles",
          "edge": "The evolution of tools and techniques is constant, but the principles have more stability and persistence."
       },
       {
          "node_1": "Project Risk Management",
          "node_2": "Discipline",
          "edge": "Risk management is a discipline that contains a series of processes to apply to both large and small projects."
       },
       {
          "node_1": "Risk Management",
          "node_2": "Project",
          "edge": "Risk management is more effective if its practice is tailored to the project."
       },
       {
          "node_1": "Risk Management",
          "node_2": "Organizational Culture, Processes and Assets",
          "edge": "The effectiveness of risk management improves when it aligns with the organizational culture, processes, and assets."
       },
       {
          "node_1": "Risk Management",
          "node_2": "Tailored to Project",
          "edge": "The practice of risk management should be tailored to each particular project."
       },
       {
          "node_1": "Project Risk Management",
          "node_2": "Global Context",
          "edge": "The principles of Project Risk Management are applicable in a global context, reflecting various business and organizational arrangements between participants."
       },
       {
          "node_1": "Principles of Project Risk Management",
          "node_2": "Check for an organization’s processes",
          "edge": "The principles of Project Risk Management can serve as a check for an organization's processes."
       },
       {
          "node_1": "Practitioners",
          "node_2": "Organization's Processes",
          "edge": "Practitioners can establish processes specific to their particular situation, project, or organization and then compare them with these principles."
       },
       {
          "node_1": "Practitioners",
          "node_2": "Good Project Risk Management Practice",
          "edge": "Practitioners can validate their processes against good Project Risk Management practice by comparing them to the described principles."
       }
   ] [
       {
           "node_1": "Project Risk Management",
           "node_2": "PMBOK Guide – Fourth Edition",
           "edge": "The Definition of Project Risk Management, as defined in the PMBOK Guide – Fourth Edition"
       },
       {
           "node_1": "Objectives of Project Risk Management",
           "node_2": "Increase probability and impact of positive events, decrease probability and impact of negative events",
           "edge": "The objectives of Project Risk Management are to increase the probability and impact of positive events, and decrease the probability and impact of negative events in the project."
       },
       {
           "node_1": "Organizational management",
           "node_2": "Project Risk Management",
           "edge": "Provides a positive potential return on investment for organizational management"
       },
       {
           "node_1": "Project stakeholders",
           "node_2": "Project Risk Management",
           "edge": "Project Risk Management should be recognized as a valuable discipline that provides a positive potential return on investment for project stakeholders."
       },
       {
           "node_1": "Project management",
           "node_2": "Project Risk Management",
           "edge": "Project Risk Management should be recognized as a valuable discipline that provides a positive potential return on investment for project management."
       },
       {
           "node_1": "Team members",
           "node_2": "Project Risk Management",
           "edge": "Project Risk Management should be recognized as a valuable discipline that provides a positive potential return on investment for team members."
       },
       {
           "node_1": "Everyone",
           "node_2": "Involved in the Project Risk Management process",
           "edge": "Open and Honest Communication — Everyone should be involved in the Project Risk Management process."
       },
       {
           "node_1": "Project Risk Management process",
           "node_2": "Actions or attitudes that hinder communication",
           "edge": "Any actions or attitudes that hinder communication about project risk reduce the effectiveness of Project Risk Management in terms of proactive approaches and effective decision-making."
       },
       {
           "node_1": "Project Risk Management activities",
           "node_2": "Value of the project to the organization",
           "edge": "Project Risk Management activities should be consistent with the value of the project to the organization and with its level of project risk."
       },
       {
           "node_1": "Project Risk Management activities",
           "node_2": "Level of project risk",
           "edge": "Project Risk Management activities should be consistent with the level of project risk."
       },
       {
           "node_1": "Project Risk Management activities",
           "node_2": "Scale of the project",
           "edge": "Project Risk Management activities should be consistent with the scale of the project."
       },
       {
           "node_1": "Project Risk Management activities",
           "node_2": "Other organizational constraints",
           "edge": "In particular, the cost of Project Risk Management should be appropriate to its potential value to the project and the organization."
       }
   ] [
       {
           "node_1": "Project Risk Management process",
           "node_2": "Practice standard",
           "edge": "The execution of the Project Risk Management process is dealt with in subsequent chapters of this practice standard."
       },
       {
           "node_1": "Project Risk",
           "node_2": "Uncertain event or condition",
           "edge": "Project risk is an uncertain event or condition"
       },
       {
           "node_1": "Project Risk",
           "node_2": "Has a positive or negative effect on a project’s objectives",
           "edge": "If it occurs, has a positive or a negative effect on a project’s objectives."
       },
       {
           "node_1": "Uncertainty dimension",
           "node_2": "Probability",
           "edge": "The uncertainty dimension may be described using the term ‘probability’"
       },
       {
           "node_1": "Effect dimension",
           "node_2": "Impact",
           "edge": "The effect may be called ‘impact’"
       },
       {
           "node_1": "Definition of risk",
           "node_2": "Distinct events",
           "edge": "Includes two key dimensions of risk: uncertainty and effect on a project’s objectives. The Definition of risk includes both distinct events which are uncertain but can be clearly described,"
       },
       {
           "node_1": "Definition of risk",
           "node_2": "More general conditions",
           "edge": "...and more general conditions which are less specific but also may give rise to uncertainty."
       },
       {
           "node_1": "Threats",
           "node_2": "Uncertain events which could have a negative effect on a project’s objectives",
           "edge": "These two types of risk are called, respectively, threats and opportunities."
       },
       {
           "node_1": "Opportunities",
           "node_2": "Uncertain events which could have a positive effect on a project’s objectives",
           "edge": "These two types of risk are called, respectively, threats and opportunities."
       },
       {
           "node_1": "Importance of a project risk",
           "node_2": "Uncertainty dimension",
           "edge": "When assessing the importance of a project risk, these two dimensions must both be considered."
       },
       {
           "node_1": "Importance of a project risk",
           "node_2": "Effect dimension",
           "edge": "When assessing the importance of a project risk, these two dimensions must both be considered."
       }
   ] [
      {
          "node_1": "Synergies",
          "node_2": "Efficiencies",
          "edge": "The context suggests that 'Synergies' and 'Efficiencies' are two benefits or positive outcomes that can be gained from a project, as they both contribute to the improvement of the project."
      },
      {
          "node_1": "Risks",
          "node_2": "Future events or conditions",
          "edge": "The context defines 'Risks' as uncertain future events or conditions."
      },
      {
          "node_1": "Causes",
          "node_2": "Events or circumstances",
          "edge": "The context equates 'Causes' with 'events or circumstances' that currently exist or are certain to exist in the future and which might give rise to risks."
      },
      {
          "node_1": "Effects",
          "node_2": "Conditional future events or conditions",
          "edge": "The context defines 'Effects' as conditional future events or conditions which would directly affect one or more project objectives if the associated risk occurs."
      },
      {
          "node_1": "Individual risks",
          "node_2": "Specific events or conditions",
          "edge": "The context explains that 'Individual risks' are specific events or conditions that might affect project objectives."
      }
   ] [
      {
          "node_1": "Individual risk",
          "node_2": "Project objectives, elements, or tasks",
          "edge": "An individual risk may positively or negatively affect one or more of the project objectives, elements, or tasks."
      },
      {
          "node_1": "Understanding individual risks",
          "node_2": "Determining effort and resources application",
          "edge": "Understanding individual risks can assist in determining how to apply effort and resources to enhance the chances of project success."
      },
      {
          "node_1": "Day-to-day Project Risk Management",
          "node_2": "Enhance the prospects of a successful project outcome",
          "edge": "Day-to-day Project Risk Management focuses on these individual risks in order to enhance the prospects of a successful project outcome."
      },
      {
          "node_1": "Overall project risk",
          "node_2": "Effect of uncertainty on the project as a whole",
          "edge": "Overall project risk represents the effect of uncertainty on the project as a whole."
      },
      {
          "node_1": "Overall project risk",
          "node_2": "Sum of individual risks on a project",
          "edge": "Overall project risk is more than the sum of individual risks on a project, since it applies to the whole project rather than to individual elements or tasks."
      },
      {
          "node_1": "Overall project risk",
          "node_2": "Exposure of stakeholders to the implications of variations in project outcome",
          "edge": "It represents the exposure of stakeholders to the implications of variations in project outcome."
      },
      {
          "node_1": "Overall project risk",
          "node_2": "Important component of strategic decision-making, program and portfolio management, and project governance",
          "edge": "It is an important component of strategic decision-making, program and portfolio management, and project governace where investments are sanctioned or cancelled and priorities are set."
      },
      {
          "node_1": "At higher levels (strategic decision-making, program and portfolio management, project governance)",
          "node_2": "Setting realistic targets for the cost and duration of a project",
          "edge": "At these higher levels, it is necessary to set realistic targets for the cost and duration of a project,"
      },
      {
          "node_1": "At higher levels (strategic decision-making, program and portfolio management, project governance)",
          "node_2": "Establishing the contingency reserve levels required to protect the project stakeholders",
          "edge": "...establish the contingency reserve levels required to protect the project stakeholders,"
      },
      {
          "node_1": "At higher levels (strategic decision-making, program and portfolio management, project governance)",
          "node_2": "Setting appropriate project priorities",
          "edge": "...set appropriate project priorities,"
      },
      {
          "node_1": "At higher levels (strategic decision-making, program and portfolio management, project governance)",
          "node_2": "Judging whether the risk of overall success is increasing or decreasing as implementation advances",
          "edge": "...judge whether the risk of overall success is increasing or decreasing as implementation advances."
      },
      {
          "node_1": "Project stakeholders' risk attitudes",
          "node_2": "Individual risk or overall project risk matters",
          "edge": "The risk attitudes of the project stakeholders determine the extent to which an individual risk or overall project risk matters."
      },
      {
          "node_1": "Project stakeholders' risk attitudes",
          "node_2": "Wide range of factors influence risk attitude",
          "edge": "A wide range of factors inﬂ uence risk attitude."
      }
   ] [
      {
          "node_1": "Project",
          "node_2": "Stakeholders' overall activities",
          "edge": "The scale of the project is within the scope of stakeholders' overall activities."
      },
      {
          "node_1": "Project",
          "node_2": "Performance of the project",
          "edge": "Public commitments are made about the performance of the project."
      },
      {
          "node_1": "Stakeholders",
          "node_2": "Environmental impacts",
          "edge": "Stakeholders' sensitivity is towards environmental impacts."
      },
      {
          "node_1": "Stakeholders",
          "node_2": "Industrial relations",
          "edge": "Stakeholders' sensitivity is towards industrial relations."
      },
      {
          "node_1": "Stakeholders",
          "node_2": "Other factors",
          "edge": "Stakeholders' sensitivity is towards other factors."
      },
      {
          "node_1": "Stakeholder risk attitudes",
          "node_2": "Desire for increased certainty in project outcomes",
          "edge": "Stakeholder risk attitudes usually result in a desire for increased certainty in project outcomes."
      },
      {
          "node_1": "Stakeholder risk attitudes",
          "node_2": "Preference for one project objective over another",
          "edge": "Stakeholder risk attitudes may express a preference for one project objective over another."
      },
      {
          "node_1": "How risk is regarded",
          "node_2": "Organization’s culture",
          "edge": "How risk is regarded is usually also strongly influenced by an organization’s culture."
      },
      {
          "node_1": "Understanding stakeholders' attitudes toward risk",
          "node_2": "Risk management planning",
          "edge": "Understanding stakeholders’ attitudes toward risk is an important component of risk management planning."
      },
      {
          "node_1": "Project Risk Management process",
          "node_2": "Optimize both project success and stakeholder satisfaction",
          "edge": "The purpose of proactively and deliberately identifying and managing stakeholders’ attitudes toward risk throughout the Project Risk Management process is to optimize both project success and stakeholder satisfaction with the project’s results."
      },
      {
          "node_1": "Stakeholder risk attitudes",
          "node_2": "Differ from one project to another for the same stakeholders",
          "edge": "Stakeholder risk attitudes may differ from one project to another for the same stakeholders."
      },
      {
          "node_1": "Stakeholder risk attitudes",
          "node_2": "Differ from one group of stakeholders to another",
          "edge": "Stakeholder risk attitudes usually differ from one group of stakeholders to another."
      },
      {
          "node_1": "Stakeholder risk attitudes",
          "node_2": "May adopt different risk attitudes at various stages in the same project",
          "edge": "A single stakeholder may adopt different risk attitudes at various stages in the same project."
      },
      {
          "node_1": "Project",
          "node_2": "International, cross-industry, or multi-organizational projects",
          "edge": "It is important to understand the particular implications of stakeholder risk attitudes on projects where the team is international, cross-industry, or multi-organizational."
      }
   ] [
       {
           "node_1": "Project Risk Management",
           "node_2": "Circumstances",
           "edge": "The nature of projects is such that circumstances change as they are being planned and executed. This includes the occurrence, non-occurrence, emergence, or discovery of risks, as well as changes in the characteristics of identified risks."
       },
       {
           "node_1": "Project Risk Management",
           "node_2": "Information",
           "edge": "The amount of information available about risks increases as time goes on during the planning and execution of a project."
       },
       {
           "node_1": "Project Risk Management Processes",
           "node_2": "Periodically",
           "edge": "The Project Risk Management processes should be repeated periodically throughout the lifetime of the project."
       },
       {
           "node_1": "Project Risk Management",
           "node_2": "Risk Response Actions Progress",
           "edge": "The progress on risk response actions should be monitored during Project Risk Management."
       },
       {
           "node_1": "Project Risk Management",
           "node_2": "Action Plans",
           "edge": "Adjustments to the action plans should be made accordingly based on the progress and changes in risks."
       },
       {
           "node_1": "Project Risk Management Planning Process",
           "node_2": "External Circumstances",
           "edge": "If external circumstances change significantly, it may be necessary to revisit the risk management planning process."
       },
       {

In [ ]:
dfg1 = graph2Df(concepts_list)
if not os.path.exists(outputdirectory):
        os.makedirs(outputdirectory)

In [ ]:
dfg1.to_csv(outputdirectory/"graph.csv", sep="|", index=False)
df.to_csv(outputdirectory/"chunks.csv", sep="|", index=False)

In [ ]:
dfg1 = pd.read_csv('TEXT_data/output/graph.csv', sep='|')
df = pd.read_csv('TEXT_data/output/chunks.csv', sep='|')

In [ ]:
dfg1.replace("", np.nan, inplace=True)
dfg1.dropna(subset=["node_1", "node_2", 'edge'], inplace=True)
dfg1['count'] = 1

In [ ]:
dfg1.shape

(783, 5)

In [ ]:
dfg1.head(5)

,node_1,node_2,edge,chunk_id,count
0,project risk management processes,pmbok guide – fourth edition,The Project Risk Management processes are defi...,36c6789384b5483a8991ed1052c5e4b5,1
1,plan risk management,chapter 1 (organizational context),Chapter 1 provides an introduction to Plan Ris...,36c6789384b5483a8991ed1052c5e4b5,1
2,perform qualitative risk analysis,chapter 2 (performance domain),Chapter 2 provides a detailed description of P...,36c6789384b5483a8991ed1052c5e4b5,1
3,plan risk responses,chapter 3 (planning domain),Chapter 3 provides a detailed description of P...,36c6789384b5483a8991ed1052c5e4b5,1
4,purpose and objectives of each process,each chapter,Each chapter in this practice standard address...,36c6789384b5483a8991ed1052c5e4b5,1

In [ ]:
def contextual_proximity(df: pd.DataFrame) -> pd.DataFrame:
    dfg_long = pd.melt(
        df, id_vars=["chunk_id"], value_vars=["node_1","node_2"], value_name="node"
    )

    dfg_long.drop(columns = ["variable"], inplace=True)
    dfg_wide = pd.merge(dfg_long, dfg_long, on="chunk_id", suffixes=("_1", "_2"))
    self_loops_drop  = dfg_wide[dfg_wide["node_1"]==dfg_wide["node_2"]].index
    dfg2 = dfg_wide.drop(index = self_loops_drop).reset_index(drop=True)

    dfg2=(
        dfg2.groupby(["node_1", "node_2"])
        .agg({"chunk_id":[",".join,"count"]})
        .reset_index()
    )

    dfg2.columns = ["node_1", "node_2", "chunk_id", "count"]
    dfg2.replace("", np.nan, inplace=True)
    dfg2.dropna(subset=["node_1", "node_2"], inplace=True)

    dfg2 = dfg2[dfg2["count"] != 1]
    dfg2["edge"] = "contextual_proximity"
    return dfg2

dfg2 = contextual_proximity(dfg1)
dfg2.tail()

,node_1,node_2,chunk_id,count,edge
19835,work breakdown structure (wbs),system dynamics analysis,"59786994019441008498f8cd0aec6917,5978699401944...",3,contextual_proximity
19836,work breakdown structure (wbs),system dynamics system (sd),"59786994019441008498f8cd0aec6917,5978699401944...",5,contextual_proximity
19848,"workshops, interviews, or questionnaires",data gathering tools,"51a83bad1dc544f68546d703a7e816e6,51a83bad1dc54...",2,contextual_proximity
19851,"workshops, interviews, or questionnaires","project planning, budgeting, and scheduling","51a83bad1dc544f68546d703a7e816e6,51a83bad1dc54...",5,contextual_proximity
19853,"workshops, interviews, or questionnaires",quantitative analysis results,"51a83bad1dc544f68546d703a7e816e6,51a83bad1dc54...",5,contextual_proximity

In [ ]:
dfg = pd.concat([dfg1, dfg2], axis = 0)
dfg = (
    dfg.groupby(["node_1", "node_2"])
    .agg({"chunk_id": ",".join, "edge": ','.join, 'count':'sum'})
    .reset_index()
)

In [ ]:
dfg.head(5)

,node_1,node_2,chunk_id,edge,count
0,'confidence',data gathering tools,"51a83bad1dc544f68546d703a7e816e6,51a83bad1dc54...",contextual_proximity,2
1,'confidence',"project planning, budgeting, and scheduling","51a83bad1dc544f68546d703a7e816e6,51a83bad1dc54...",contextual_proximity,5
2,'confidence',quantitative analysis results,"51a83bad1dc544f68546d703a7e816e6,51a83bad1dc54...",contextual_proximity,5
3,'correlation between risks',data gathering tools,"51a83bad1dc544f68546d703a7e816e6,51a83bad1dc54...",contextual_proximity,2
4,'correlation between risks',"project planning, budgeting, and scheduling","51a83bad1dc544f68546d703a7e816e6,51a83bad1dc54...",contextual_proximity,5

# Calculate the NetworkX Graph

In [ ]:
nodes = pd.concat([dfg['node_1'], dfg['node_2']], axis = 0).unique()
nodes.shape

(993,)

In [ ]:
import networkx as nx
G = nx.Graph()

for node in nodes:
    G.add_node(
        str(node)
    )

for index, row in dfg.iterrows():
    G.add_edge(
        str(row["node_1"]),
        str(row["node_2"]),
        title=row["edge"],
        weight=row['count']
    )

#### Calculate communities for coloring nodes

In [ ]:
communities_generator = nx.community.girvan_newman(G)
top_level_communities = next(communities_generator)
next_level_communities = next(communities_generator)
communities = sorted(map(sorted, next_level_communities))

print("Number of Communities:", len(communities))
print(communities)

100%|██████████| 3/3 [02:02<00:00, 40.82s/it]

Number of Communities: 39

#### Create a dataframe for community colors

In [ ]:
import seaborn as sns
palette = "hls"

def colors2Community(communities) -> pd.DataFrame:

    p=sns.color_palette(palette, len(communities)).as_hex()
    random.shuffle(p)
    rows = []
    group=0

    for community in communities:
        color = p.pop()
        group+=1
        
        for node in community:
            rows += [{"node": node, "color": color, "group": group}]
    
    df_colors = pd.DataFrame(rows)
    return df_colors

In [ ]:
colors = colors2Community(communities)
colors.head(5)

                                                node    color  group
0                                       'confidence'  #8cdb57      1
1                        'correlation between risks'  #8cdb57      1
2             'expected value of a project decision'  #8cdb57      1
3  'identity or location within the project model...  #8cdb57      1
4  'probability distribution of its potential imp...  #8cdb57      1

#### Add colors to the graph

In [ ]:
for index, row in colors.iterrows():
    G.nodes[row['node']]['group'] = row['group']
    G.nodes[row['node']]['color'] = row['color']
    G.nodes[row['node']]['size'] = G.degree[row['node']]

In [ ]:
from pyvis.network import Network

In [ ]:
graph_output_directory = "./docs/index.html"

net = Network (
    notebook = False,
    cdn_resources = "remote",
    height = "900px",
    width = "100%",
    select_menu = True,
    filter_menu = False,
)

In [ ]:
net.from_nx(G)
net.force_atlas_2based(central_gravity = 0.015, gravity = -31)
net.show_buttons(filter_= ["physics"])
net.show(graph_output_directory, notebook=False)

./docs/index.html